<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Publication;
use App\Models\Category;

class PublicationSeeder extends Seeder
{
    public function run(): void
    {
       $publications = [
            [
                'title' => 'Tamil Civilization and Heritage',
                'title_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHFsRGq5FcTGZFe2f8TimfwFKbCbgREX7lSw&s',
                'content' => 'An in-depth study of ancient Tamil civilization and heritage',
                'main_category_id' => 1,
                'subcategory_id' => 1,
                'price' => 0,
                'visibleType' => 'private',
                'pdf' => null,
            ],
            [
                'title' => 'Tamil Literature Through Ages',
                'title_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDYd0IEonnsFXBQ85Qy1HMKZw2YKLzDxSoig&s',
                'content' => 'Evolution of Tamil literature from Sangam to modern era',
                'main_category_id' => 1,
                'subcategory_id' => 2,
                'price' => 24.99,
                'visibleType' => 'private',
                'pdf' => null,
            ],
            [
                'title' => 'Tamil Nadu Cultural Report',
                'title_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzPHKmg4f-70i7YjB_YBZvWloD7GgSkQkzdQ&s',
                'content' => 'Annual report on Tamil Nadu culture and traditions',
                'main_category_id' => 2,
                'subcategory_id' => 3,
                'price' => 0,
                'visibleType' => 'public',
                'pdf' => null,
            ],
            [
                'title' => 'History of Tamil Kingdoms',
                'title_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWHQKy7593vgcssc3wysdfji0anYRa6GBr2g&s',
                'content' => 'Chola, Chera, and Pandya dynasties explained',
                'main_category_id' => 1,
                'subcategory_id' => 1,
                'price' => 34.99,
                'visibleType' => 'private',
                'pdf' => null,
            ],
            [
                'title' => 'Tamil Studies Journal',
                'title_image' => 'https://ijtllsml.wordpress.com/wp-content/uploads/2017/05/b8rnurvccaesyop.jpg',
                'content' => 'Academic journal on Tamil studies and research',
                'main_category_id' => 2,
                'subcategory_id' => 3,
                'price' => 0,
                'visibleType' => 'public',
                'pdf' => null,
            ],
            [
                'title' => 'Guide to Tamil Cultural Practices',
                'title_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREGTpJld3J0htnO6SqsKDUYYdAdPxM0M-21A&s',
                'content' => 'Festivals, rituals, and traditional practices',
                'main_category_id' => 1,
                'subcategory_id' => 2,
                'price' => 19.99,
                'visibleType' => 'private',
                'pdf' => null,
            ],
            [
                'title' => 'Tamil Community Magazine',
                'title_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSaI43_U5HGTzdgHbRu6ieDqBEpPxMcPMSWqw&s',
                'content' => 'Stories and news from Tamil communities worldwide',
                'main_category_id' => 2,
                'subcategory_id' => 3,
                'price' => 0,
                'visibleType' => 'public',
                'pdf' => null,
            ],
            [
                'title' => 'Learning the Tamil Language',
                'title_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwDY9lGpZ61BjF7IaGQPfV8gZX7EQfAB4LNg&s',
                'content' => 'Structured guide for learning Tamil language basics',
                'main_category_id' => 1,
                'subcategory_id' => 2,
                'price' => 21.99,
                'visibleType' => 'private',
                'pdf' => null,
            ],
            [
                'title' => 'Modern Tamil Poetry Collection',
                'title_image' => 'https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d',
                'content' => 'Selected modern poetry inspired by Tamil themes',
                'main_category_id' => 1,
                'subcategory_id' => 1,
                'price' => 0,
                'visibleType' => 'public',
                'pdf' => null,
            ],

             // Next 10 publications
            [
                'title' => 'Tamil Economy and Society Report',
                'title_image' => 'https://ancienttamilcivilization.wordpress.com/wp-content/uploads/2015/03/lost-continent-of-kumari-kandam.jpg',
                'content' => 'Economic and social analysis of Tamil regions',
                'main_category_id' => 3,
                'subcategory_id' => 5,
                'price' => 14.99,
                'visibleType' => 'private',
                'pdf' => null,
            ],
            [
                'title' => 'Tamil Art and Architecture',
                'title_image' => 'https://telibrary.com/wp-content/uploads/2020/12/tamil-ar.jpeg',
                'content' => 'Traditional and modern Tamil art forms',
                'main_category_id' => 2,
                'subcategory_id' => 4,
                'price' => 0,
                'visibleType' => 'private',
                'pdf' => null,
            ],
            [
                'title' => 'Open Educational Resources on Tamil Studies',
                'title_image' => 'https://images.nationalgeographic.org/image/upload/v1638892233/EducationHub/photos/brihadishwara-temple.jpg',
                'content' => 'Free learning resources related to Tamil studies',
                'main_category_id' => 1,
                'subcategory_id' => 2,
                'price' => 0,
                'visibleType' => 'public',
                'pdf' => null,
            ],
            [
                'title' => 'Tamil Folk Tales',
                'title_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJCF889_MHwWwUeJe_G8oD0CeePYnBbGsxmQ&s',
                'content' => 'Collection of Tamil folk stories and legends',
                'main_category_id' => 1,
                'subcategory_id' => 1,
                'price' => 0,
                'visibleType' => 'public',
                'pdf' => null,
            ],
            [
                'title' => 'Modern Tamil Cinema Insights',
                'title_image' => 'https://ling-app.com/wp-content/uploads/2025/03/Tamil-books_Ling-app_a-stack-of-old-Tamil-books.jpg',
                'content' => 'Analysis of contemporary Tamil films',
                'main_category_id' => 2,
                'subcategory_id' => 4,
                'price' => 9.99,
                'visibleType' => 'private',
                'pdf' => null,
            ],
            [
                'title' => 'Tamil Language Grammar Guide',
                'title_image' => 'https://images.unsplash.com/photo-1581091870621-5c69d4c7c946',
                'content' => 'Detailed guide to Tamil grammar rules',
                'main_category_id' => 1,
                'subcategory_id' => 2,
                'price' => 12.50,
                'visibleType' => 'private',
                'pdf' => null,
            ],
            [
                'title' => 'Tamil Music Heritage',
                'title_image' => 'https://telibrary.com/wp-content/uploads/2021/05/thol-365x300.jpg',
                'content' => 'Exploring traditional and modern Tamil music',
                'main_category_id' => 2,
                'subcategory_id' => 4,
                'price' => 0,
                'visibleType' => 'public',
                'pdf' => null,
            ],
            [
                'title' => 'Tamil Festivals and Rituals',
                'title_image' => 'https://img.freepik.com/premium-photo/illustration-pongal-day-harvest-festival-tamil-nadu-south-india-pongal-makar-sankranti-festival-ai-generated-image_718265-6343.jpg',
                'content' => 'Comprehensive guide to Tamil festivals and rituals',
                'main_category_id' => 1,
                'subcategory_id' => 2,
                'price' => 19.99,
                'visibleType' => 'private',
                'pdf' => null,
            ],
            [
                'title' => 'Tamil Nadu Travel Guide',
                'title_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGdwdRJ1WXHEdnCud6kLenRuTMW3Efrc8XVA&s',
                'content' => 'Tourist destinations and cultural insights',
                'main_category_id' => 4,
                'subcategory_id' => 4,
                'price' => 0,
                'visibleType' => 'public',
                'pdf' => null,
            ],
            [
                'title' => 'Tamil Philosophy and Ethics',
                'title_image' => 'https://images.unsplash.com/photo-1525011268546-bf6e3b1e6c7c',
                'content' => 'Study of Tamil philosophical texts and moral principles',
                'main_category_id' => 3,
                'subcategory_id' => 5,
                'price' => 15.00,
                'visibleType' => 'private',
                'pdf' => null,
            ],

            [
                'title' => 'Tamil Economy and Society Report',
                'title_image' => 'https://ijtllsml.wordpress.com/wp-content/uploads/2017/05/b8rnurvccaesyop.jpg',
                'content' => 'Economic and social analysis of Tamil regions',
                'main_category_id' => 3,
                'subcategory_id' => 5,
                'price' => 14.99,
                'visibleType' => 'private',
                'pdf' => null,
            ],
            [
                'title' => 'Tamil Art and Architecture',
                'title_image' => 'https://ijtllsml.wordpress.com/wp-content/uploads/2017/05/b8rnurvccaesyop.jpg',
                'content' => 'Traditional and modern Tamil art forms',
                'main_category_id' => 2,
                'subcategory_id' => 4,
                'price' => 0,
                'visibleType' => 'private',
                'pdf' => null,
            ],
            [
                'title' => 'Open Educational Resources on Tamil Studies',
                'title_image' => 'https://images.unsplash.com/photo-1529070538774-1843cb3265df',
                'content' => 'Free learning resources related to Tamil studies',
                'main_category_id' => 1,
                'subcategory_id' => 2,
                'price' => 0,
                'visibleType' => 'public',
                'pdf' => null,
            ],
            [
                'title' => 'Tamil Folk Tales',
                'title_image' => 'https://images.unsplash.com/photo-1581092795365-d4b3f1d46f13',
                'content' => 'Collection of Tamil folk stories and legends',
                'main_category_id' => 1,
                'subcategory_id' => 1,
                'price' => 0,
                'visibleType' => 'public',
                'pdf' => null,
            ],
            [
                'title' => 'Modern Tamil Cinema Insights',
                'title_image' => 'https://images.unsplash.com/photo-1605902711622-cfb43c4431ee',
                'content' => 'Analysis of contemporary Tamil films',
                'main_category_id' => 2,
                'subcategory_id' => 4,
                'price' => 9.99,
                'visibleType' => 'private',
                'pdf' => null,
            ],
            [
                'title' => 'Tamil Language Grammar Guide',
                'title_image' => 'https://images.unsplash.com/photo-1581091870621-5c69d4c7c946',
                'content' => 'Detailed guide to Tamil grammar rules',
                'main_category_id' => 1,
                'subcategory_id' => 2,
                'price' => 12.50,
                'visibleType' => 'private',
                'pdf' => null,
            ],
            [
                'title' => 'Tamil Music Heritage',
                'title_image' => 'https://images.unsplash.com/photo-1511376777868-611b54f68947',
                'content' => 'Exploring traditional and modern Tamil music',
                'main_category_id' => 2,
                'subcategory_id' => 4,
                'price' => 0,
                'visibleType' => 'public',
                'pdf' => null,
            ],
            [
                'title' => 'Tamil Festivals and Rituals',
                'title_image' => 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1',
                'content' => 'Comprehensive guide to Tamil festivals and rituals',
                'main_category_id' => 1,
                'subcategory_id' => 2,
                'price' => 19.99,
                'visibleType' => 'private',
                'pdf' => null,
            ],
            [
                'title' => 'Tamil Nadu Travel Guide',
                'title_image' => 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee',
                'content' => 'Tourist destinations and cultural insights',
                'main_category_id' => 4,
                'subcategory_id' => 4,
                'price' => 0,
                'visibleType' => 'public',
                'pdf' => null,
            ],
            [
                'title' => 'Tamil Philosophy and Ethics',
                'title_image' => 'https://images.unsplash.com/photo-1525011268546-bf6e3b1e6c7c',
                'content' => 'Study of Tamil philosophical texts and moral principles',
                'main_category_id' => 3,
                'subcategory_id' => 5,
                'price' => 15.00,
                'visibleType' => 'private',
                'pdf' => null,
            ],
        ];

        foreach ($publications as $publication) {
            Publication::create($publication);
        }
    }
}
